### ISSUE TITLE
Change QueryPaymentDetails endpoint request to use https in development

### ISSUE THREAD

**Issue by pette9** [itsmrwave/pesapal-gem#17]
It appears like pesapal has moved the `QueryPaymentDetails` endpoint for the demo to `https` when you make the request using http as it is currently in the gem, the response is in html format with a message that the resource has been moved to a `https` url.

**Comment by dmric** [comment]
Use `gem 'pesapal', git: 'https://github.com/dmric/pesapal-gem.git'` for now as the fix gets merged.

**Comment by itsmrwave** [comment]
@pette9 @dmric I missed this issue and [the PR](https://github.com/itsmrwave/pesapal-gem/issues/18). But [the issue has been brought to my attention] by @Alfred-W.

On it. Sorry guys.

**Comment by itsmrwave** [comment]
Fixed in https://github.com/itsmrwave/pesapal-gem/pull/18.

**Comment by itsmrwave** [comment]
@pette9 Version 1.7.0 has been released and includes this fix:
https://rubygems.org/gems/pesapal/versions/1.7.0

cc: @dmric

**Comment by pette9** [comment]
Thank you for this.

**Comment by itsmrwave** [comment]
@pette9 Unrelated. You'll probably want to install version 1.8.0:
https://rubygems.org/gems/pesapal/versions/1.8.0

It contains [an important security fix][1].

[1]: https://github.com/itsmrwave/pesapal-gem/pull/21/commits/29fb90b70d6a30fa3f23d162ad31ac87034e3abc

**Comment by pette9** [comment]
sawa.
